exclude: [
    'bison_cppml.py',
    'boost.py',
    'coffeelint.json',
    'configure_cpp.py',
    'core.none',
    'cppml',
    'cppml.py',
    'distcc.py',
    'docker',
    'gcov.py',
    'gcovr',
    'gcovWrapper.py',
    'generateCore.gdb',
    'license',
    'LICENSE',
    'lint.sh',
    'make.sh',
    'mesos',
    'ocaml.py',
    'packages',
    'README.md',
    'test.py',
    'test_scripts',
    'third_party',
    'ufora',
    'waf',
    'wscript'
    ]
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
baseurl: /ufora
