markdown: redcarpet
redcarpet:
  extensions: [
    'tables',
    'fenced_code_blocks',
    'no_intra_emphasis',
    'autolink',
    'strikethrough',
    'with_toc_data',
    'footnotes'
  ]
baseurl: /ufora
sass:
  sass_dir: _sass
categories: [tutorial, doc, develop]
